blog/blog/apps/dadova/urls.py
from . import views
from django.urls import path


app_name = 'dadova'
urlpatterns = [
	path('register/', views.register, name='register'),
	path('user_login/', views.user_login, name='login'),
	path('', views.home, name='home'),
	path('<int:post_id>/<int:user_id>/', views.PostDetail.as_view(), name='post_detail'),
	path('about/', views.about, name='about'),
	path('contact_us/', views.contact_us, name='contact_us'),
	path('<str:slug>/', views.show_category_posts, name='show_category_posts'),
	path('<int:post_id>/<int:user_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dadova/', include('dadova.urls')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/apps/dadova/models.py
# complete
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):

	name = models.CharField('Имя категории', max_length=255)
	slug = models.SlugField(unique=True)

	def __str__(self):

		return self.name

	class Meta:
		verbose_name_plural = 'Categories'


class Post(models.Model):

	category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True)

	title = models.CharField('Название поста', max_length=255)
	subtitle = models.CharField('Подназвание поста', max_length=255)
	text = models.TextField('Текст поста')
	pub_date = models.DateField('Дата публикации')
	is_featured = models.BooleanField(default=False, null=True)
	img = models.ImageField('Изображение', null=True)

	def __str__(self):

		return self.title


class Comment(models.Model):

	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	author_name = models.ForeignKey(User, on_delete=models.CASCADE)
	text = models.TextField('Текст комментария')

blog/blog/apps/dadova/forms.py
from django.contrib.auth.models import User
from django import forms


class UserRegistrationForm(forms.ModelForm):
    
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

blog/blog/apps/dadova/views.py
# complete
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Post, Category, Comment
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic import RedirectView
from django.core.paginator import Paginator
from .forms import *
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'dadova/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'dadova/register.html', {'user_form': user_form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'dadova/login_done.html', {'user': user})
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'dadova/login.html', {'form': form})


def home(request):

	posts = Post.objects.order_by('-pub_date')

	paginator = Paginator(posts, 2)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	categories = Category.objects.all()

	return render(request, 'base.html', {'page_obj': page_obj, 'posts': posts, 'categories': categories})


def about(request):

	return render(request, 'dadova/about.html')


def contact_us(request):

	return render(request, 'dadova/contact.html')

	
def show_category_posts(request, slug):
	
	category = Category.objects.get(slug=slug)

	c = Category.objects.get(slug=slug).post_set.order_by('-pub_date')
		
	paginator = Paginator(c, 2)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
		
	return render(request, 'dadova/category.html', {'page_obj': page_obj, 'cat_posts': c, 'category': category})


class PostDetail(DetailView):

	model = Post
	template_name = 'dadova/detail.html'

	def get(self, request, post_id, *args, **kwargs):

		post = Post.objects.get(id=post_id)
		categories = Category.objects.all()
		comments = post.comment_set.order_by('-id')[:10]
		context = {
			'post': post,
			'categories': categories,
			'comments': comments,
		}

		return render(request, self.template_name, context=context)


def leave_comment(request, post_id, user_id):

	try:
		p = Post.objects.get(id=post_id)
		u = User.objects.get(id=user_id)
	except:
		raise Http404()

	p.comment_set.create(author_name=u, text=request.POST['text'])
	return HttpResponseRedirect(reverse('dadova:post_detail', args=(p.id, u.id, )))

blog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Home</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Blog_Site</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:contact_us' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:login' %}">Sign In</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:register' %}">Sign Up</a></li>
                        {% if user.id != None %}
                        	<li class="nav-item"><a class="nav-link">{{ user.username }}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        {% block content %}
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Welcome to Blog Home!</h1>
                    <p class="lead mb-0">Blog Homepage</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
            
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    {% for post in posts %}
                        {% if post.is_featured %}
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="{{ post.img.url }}" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">{{ post.pub_date }}</div>
                                    <h2 class="card-title">{{ post.title }}</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                                    {% if user.id != None %}
                                    <a class="btn btn-primary" href="{% url 'dadova:post_detail' post.id user.id %}">Read more →</a>
                                    {% else %}
                                    <a class="btn btn-primary" href="{% url 'dadova:register' %}">Register →</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                        <div class="col-lg-6">
                            <!-- Blog post-->
                            {% for post in page_obj %}
                                <div class="card mb-4">
                                    <a href="#!"><img class="card-img-top" src="{{ post.img.url }}" alt="..." /></a>
                                    <div class="card-body">
                                        <div class="small text-muted">{{ post.pub_date }}</div>
                                        <h2 class="card-title h4">{{ post.title }}</h2>
                                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                                        {% if user.id != None %}
                                    	<a class="btn btn-primary" href="{% url 'dadova:post_detail' post.id user.id %}">Read more →</a>
                                    	{% else %}
                                    	<a class="btn btn-primary" href="{% url 'dadova:register' %}">Register →</a>
                                    	{% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Pagination-->
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Newer</a></li>
                            {% endif %}

                            {% if page_obj.has_other_pages %}

                                {% for p in page_obj.paginator.page_range %}

                                    {% if page_obj.number == p %}

                                        <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>

                                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                                
                                        <li class="page-item" aria-current="page"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>

                                    {% endif %}

                                {% endfor %}

                            {% endif %}

                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Older</a></li>
                            {% endif %}
                            
                        </ul>
                    </nav>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">

                                        {% for category in categories %}

                                            <li><a href="{% url 'dadova:show_category_posts' category.slug %}">{{ category.name }}</a></li>

                                        {% endfor %}
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets!</div>
                    </div>
                </div>
            
            </div>
        {% endblock %}
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    </body>
</html>

blog/blog/templates/dadova/category.html
{% extends 'base.html' %}

{% block title %}{% endblock %}


{% block content %}

    <header class="py-5 bg-light border-bottom mb-4">
        <div class="container">
            <div class="text-center my-5">
                <h1 class="fw-bolder">{{ category.name }}</h1>
                <p class="lead mb-0">Blog Categorypage</p>
            </div>
        </div>
    </header>

    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <!-- Blog post-->
                {% for post in page_obj %}
                    <div class="card mb-4">
                        <a href="#!"><img class="card-img-top" src="{{ post.img.url }}" alt="..." /></a>
                        <div class="card-body">
                            <div class="small text-muted">{{ post.pub_date }}</div>
                            <h2 class="card-title h4">{{ post.title }}</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                            {% if user.id != None %}
                            <a class="btn btn-primary" href="{% url 'dadova:post_detail' post.id user.id %}">Read more →</a>
                            {% else %}
                            <a class="btn btn-primary" href="{% url 'dadova:register' %}">Register →</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <nav aria-label="Pagination">
            <hr class="my-0" />
            <ul class="pagination justify-content-center my-4">
                            
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Newer</a></li>
                {% endif %}

                {% if page_obj.has_other_pages %}

                    {% for p in page_obj.paginator.page_range %}

                        {% if page_obj.number == p %}

                            <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>

                        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                                
                            <li class="page-item" aria-current="page"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>

                        {% endif %}

                    {% endfor %}

                {% endif %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Older</a></li>
                {% endif %}
                            
            </ul>
        </nav>

    </div><br>

{% endblock %}

blog/blog/templates/dadova/contact.html
{% extends 'base.html' %}

{% block title %}{% endblock %}


{% block content %}

    <header class="py-5 bg-light border-bottom mb-4">
        <div class="container">
            <div class="text-center my-5">
                <h1 class="fw-bolder">Contact With Us</h1>
                <p class="lead mb-0">Blog Contactpage</p>
            </div>
        </div>
    </header>

    <div class="container">

    <form method="POST">
        
        {% csrf_token %}

        <input class="form-control" type="email" required="" placeholder="E-Mail"><br>
        <input class="form-control" type="text" required="" placeholder="Name"><br>
        <input class="form-control" type="tel" required="" placeholder="Phone Number" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"><br>
        <button class="btn btn-primary" type="submit">Send</button>

    </form>

    </div><br>

{% endblock %}

blog/blog/templates/dadova/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Post</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"crossorigin="anonymous">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Blog Post</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:contact_us' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:login' %}">Sign In</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'dadova:register' %}">Sign Up</a></li>
                        {% if user.id != None %}
                            <li class="nav-item"><a class="nav-link">{{ user.username }}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">Welcome to {{ post.title }}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{ post.pub_date }}</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="">Web Design</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="">Freebies</a>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{ post.img.url }}" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                            <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                            <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                            <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                            <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                            <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if user.id != None %}
                                <form class="mb-4" action="{% url 'dadova:leave_comment' post.id user.id %}" method="POST">

                                    {% csrf_token %}

                                    <textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!" name="text"></textarea><br>
                                    <button class="btn btn-primary" type="submit">Leave Commment</button>

                                </form>
                                {% else %}
                                <form class="mb-4" action="{% url 'dadova:register' %}" method="POST">

                                    {% csrf_token %}

                                    <textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!" name="text"></textarea><br>
                                    <button class="btn btn-primary" type="submit">Leave Commment</button>

                                </form>
                                {% endif %}
                                
                                <!-- Comment with nested comments-->
                                {% for comment in comments %}
                                    <div class="d-flex mb-4">
                                        <!-- Parent comment-->
                                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                        <div class="ms-3">
                                        
                                            <div class="fw-bold">{{ comment.author_name }}</div>
                                        
                                            {{ comment.text }}

                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">

                                        {% for category in categories %}

                                            <li><a href="{% url 'dadova:show_category_posts' category.slug %}">{{ category.name }}</a></li>

                                        {% endfor %}
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets!</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    </body>
</html>

blog/blog/templates/dadova/home.html
{% extends 'base.html' %}

{% block title %}{% endblock %}


{% block content %}


    {% for post in posts %}
    	<div class="post-preview">
        	<a href="{% url 'dadova:post_detail' post.id %}">
            	<h2 class="post-title">{{ post.title }}</h2>
            	<h3 class="post-subtitle">{{ post.subtitle }}</h3>
        	</a>
        	<p class="post-meta">
            	Posted by
            	<a href="#!">Blog Site</a>
            	on September 24, 2021
        	</p>
    	</div>
    	<!-- Divider-->
    	<hr class="my-4" />
    {% endfor %}


{% endblock %}

blog/blog/templates/dadova/login.html
{% extends 'base.html' %}
{% block title %}Log-in{% endblock %}
{% block content %}
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log-in"></p>
    </form>
{% endblock %}

blog/blog/templates/dadova/login_done.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ user.first_name }}!</h1>
{% endblock %}

blog/blog/templates/dadova/register.html
{% extends 'base.html' %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}

blog/blog/templates/dadova/register_done.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created. Now you can <a href="{% url 'dadova:login' %}">log in</a>.</p>
{% endblock %}